name: viz
channels:
  - conda-forge
  - bioconda
  - defaults
  - R
dependencies:
  - r-base=4.3.3
  - r-tidyverse=2.0.0
  - r-here=1.0.1
  - r-fixest=0.12.1
  - r-readxl=1.4.3
  - r-progressr=0.14.0
  - r-texreg=1.39.4
  - r-pacman=0.5.1
  - r-sf=1.0.16
  - wget=1.20.3
  - snakemake=8.18.2
  - graphviz=5.0.1
  - python=3.12.3
