FROM hchulkim/r_4.5.1:latest

# Get architecture variable
ARG TARGETARCH
ENV ARCH_TYPE=${TARGETARCH}

# Quarto
ENV QUARTO_VERSION=1.7.32
RUN /rocker_scripts/install_quarto.sh

# --- TinyTeX install (arm64 manual, amd64 via Quarto) ---
RUN set -eux; \
  if [ "$ARCH_TYPE" = "arm64" ]; then \
    wget -qO- "https://yihui.org/tinytex/install-unx.sh" | sh -s - --admin --no-path; \
  else \
    quarto install tinytex; \
  fi

# Set TinyTeX path
ENV PATH="/root/.TinyTeX/bin/aarch64-linux:/root/.TinyTeX/bin/x86_64-linux:${PATH}"

# Set CTAN mirror for tlmgr
ENV TEXLIVE_REPOSITORY="https://ctan.math.illinois.edu/systems/texlive/tlnet"

# Set repo in tlmgr
RUN tlmgr option repository "$TEXLIVE_REPOSITORY"; \
  tlmgr update --self; \
  tlmgr update --all
# -------------------------------------------------------

# Julia
ENV JULIA_VERSION=1.11.6
RUN /rocker_scripts/install_julia.sh
RUN julia -e "import Pkg; Pkg.add(\"DrWatson\")"
