---
title: "report"
author: "Hyoungchul Kim"
date: today
execute:
  echo: false
format: 
  html:
    toc: true
    number-sections: true
    keep-html: true
    code-overflow: wrap
  pdf:
    pdf-engine: pdflatex
    keep-tex: true
    fig-pos: H
    include-in-header: 
       text: |
         \usepackage{fvextra}
         \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
         \DefineVerbatimEnvironment{OutputCode}{Verbatim}{breaklines,commandchars=\\\{\}}
         \usepackage{booktabs}
         \usepackage{longtable}
         \usepackage{array}
         \usepackage{multirow}
         \usepackage{wrapfig}
         \usepackage{float}
         \usepackage{colortbl}
         \usepackage{pdflscape}
         \usepackage{tabu}
         \usepackage{threeparttable}
         \usepackage{threeparttablex}
         \usepackage[normalem]{ulem}
         \usepackage{makecell}
         \usepackage{xcolor}
         
---

# Lorem ipsum

## Bullet point

This is a template for my report.

1. Lorem.

- Lorem.

## Math equations

This is a latex math-equation using *align*.

\begin{align*}
  (1) + (2) + (3) \geq 3
\end{align*}

--

## Tables

```{r}
#| warning: false
#| message: false

library(fixest)
  mods = feols(
  rating ~ complaints + privileges + learning + csw0(raises + critical), data = attitude
)

dict = c("rating"     = "Overall Rating",
         "complaints" = "Handling of Complaints",
         "privileges" = "No Special Priviledges",
         "learning"   = "Opportunity to Learn",
         "raises"     = "Performance-Based Raises",
         "critical"   = "Too Critical")

library(modelsummary) # Make sure you have >=v2.0.0

modelsummary(
  setNames(mods, c("(1)", "(2)")),
  coef_map = dict, stars = TRUE,
  gof_map = NA
  ) |>
  # some optional stylistic tweaks
  tinytable::group_tt(j = list("Dep. variable: Overall Rating" = 2:3)) |>
  tinytable::style_tt(i = 1:2, j = 2:3, background = "pink")
```

## kableExtra tables

```{r}

library(kableExtra)

mtcars |> 
  kbl(format = "html")

```

